apiVersion: apps/v1
kind: Deployment
metadata:
  name: laos-graphql-playground
  labels:
    app.kubernetes.io/app: laos-graphql-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: laos-graphql-playground
  template:
    metadata:
      labels:
        app.kubernetes.io/app: laos-graphql-playground
    spec:
      containers:
        - name: laos-graphql-playground
          image: freeverseio/laos-graphql-playground:{{ .Values.imageTag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:             
            - name: API_ENDPOINT
              value: {{ .Values.graphqlEndpoint }}
          ports:
            - containerPort: 80
      volumes:
        - name: api-keys
          configMap:
            name: api-keys