apiVersion: apps/v1
kind: Deployment
metadata:
  name: laos-client-api
  labels:
    app.kubernetes.io/app: laos-client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: laos-client-api
  template:
    metadata:
      labels:
        app.kubernetes.io/app: laos-client-api
    spec:
      containers:
        - name: laos-client-api
          image: freeverseio/laos-client-api:{{ .Values.imageTag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: db-certificate
              mountPath: "/app/data"
              readOnly: true
          resources:
            requests:
              memory: '256Mi'
              cpu: '1'
            limits:
              memory: '512Mi'
              cpu: '2'
          env:  
            - name: ROOT_DIR
              value: "/app"
            - name: GQL_PORT
              value: "4001"
            - name: INDEXER_POLYGON_ENDPOINT
              value: "http://indexer-laos-polygon-api.protostar.svc.cluster.local:4000/graphql"
            - name: INDEXER_ETHEREUM_ENDPOINT
              value: "http://indexer-laos-ethereum-api.protostar.svc.cluster.local:4000/graphql"
            - name: MINTER_PVK
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: minterPvk
            - name: RPC_MINTER
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: rpcMinter
            - name: PINATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: pinataApiKey
            - name: PINATA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: pinataApiSecret
            - name: MINTER_KEYS
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: clientApiMinterKeys
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: protostar-private-config
                  key: postgresPassword
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgresUser }}:$(POSTGRES_PASSWORD)@{{.Values.postgresHost}}:{{.Values.postgresPort}}/{{.Values.postgresDb}}?sslmode=require&sslrootcert=./data/ca-certificate.pem"            
          ports:
            - containerPort: 4001
      volumes:
        - name: db-certificate
          secret:
            secretName: db-certificate