apiVersion: v1
kind: Service
metadata:
  name: laos-client-api
  labels:
    app.kubernetes.io/app: laos-client-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/app: laos-client-api
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: api
  
