version: 2.1

orbs:
  kube-orb: circleci/kubernetes@1.3.1
  helm: circleci/helm@3.0.2

commands:
  install-helmfile:
    description: Install helmfile
    steps:
      - run:
          name: Install helmfile
          command: ./_circleci-scripts/install-helmfile.sh

  dockerize-and-push:
    parameters:
      image:
        type: string
      root:
        type: string
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWD | docker login -u $DOCKER_ID --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            cd << parameters.root >>
            echo "Docker images for $CIRCLE_SHA1 will be pushed"
            docker build -t << parameters.image >>:$CIRCLE_SHA1 .
            docker push << parameters.image >>:$CIRCLE_SHA1

jobs:
  deploy_to_cluster:
    parameters:
      environment:
        type: string
        default: development
      root:
        type: string
    description: Deploy to << parameters.environment >> environment
    docker:
      - image: cimg/deploy:2023.09
    steps:
      - checkout
      - kube-orb/install-kubectl:
          kubectl-version: 'v1.25.14'
      - when:
          condition:
            equal: [ development, << parameters.environment >> ]
          steps:
            - kube-orb/install-kubeconfig:
                kubeconfig: KUBECONFIG_DATA
      - when:
          condition:
            equal: [ staging, << parameters.environment >> ]
          steps:
            - kube-orb/install-kubeconfig:
                kubeconfig: KUBECONFIG_PROTOSTAR_STG_DATA
      - helm/install_helm_client:
          version: v3.13.0
      - install-helmfile
      - run:
          name: Deploy to << parameters.environment >> environment
          command: |
            cd << parameters.root >>
            helmfile sync --environment << parameters.environment >>

  deployment-test:
    docker:
      - image: cimg/base:2022.08
    steps:
      - checkout
      - helm/install_helm_client:
          version: v3.13.0
      - install-helmfile
      - run:
          name: Test Helmfile
          command: |
            cd _deployment
            helmfile lint

  build-app:
    parameters:
      image:
        type: string
      root:
        type: string
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Deploy Node API
          command: |
            cd << parameters.root >>
      - dockerize-and-push:
          image: << parameters.image >>
          root: << parameters.root >>

workflows:
  ci-workflow:
    jobs:
      - build-app:
          name: build-client-api
          image: freeverseio/laos-client-api
          root: laos-client-api
          context: dockerhub
          # filters:
          #   branches:
          #     only:
          #       - main

      - build-app:
          name: build-api-gateway
          image: freeverseio/laos-api-gateway
          root: laos-api-gateway
          context: dockerhub
          # filters:
          #   branches:
          #     only:
          #       - main

      - build-app:
          name: build-playground
          image: freeverseio/laos-graphql-playground
          root: graphql-playground
          context: dockerhub
          # filters:
          #   branches:
          #     only:
          #       - main

      - build-app:
          name: build-indexer
          image: freeverseio/laos-indexer
          root: laos-indexer
          context: dockerhub
          # filters:
          #   branches:
          #     only:
          #       - main

      - deployment-test

      - approval:
          type: approval
          name: approve-deploy-client-api
          requires:
            - deployment-test
            - build-client-api
            - build-api-gateway
            - build-playground
          # filters:
          #   branches:
          #     only:
          #       - main

      - approval:
          type: approval
          name: approve-deploy-client-api-staging
          requires:
            - deployment-test
            - build-client-api
            - build-api-gateway
            - build-playground
          # filters:
          #   branches:
          #     only:
          #       - main

      - approval:
          type: approval
          name: approve-deploy-indexer
          requires:
            - deployment-test
            - build-indexer
          # filters:
          #   branches:
          #     only:
          #       - main
      
      - approval:
          type: approval
          name: approve-deploy-indexer-staging
          requires:
            - deployment-test
            - build-indexer
          # filters:
          #   branches:
          #     only:
          #       - main

      - deploy_to_cluster:
          name: deploy-to-dev-api
          requires:
            - deployment-test
            - approve-deploy-client-api

          environment: development
          root: _deployment
          # filters:
          #   branches:
          #     only:
          #       - main
      
      - deploy_to_cluster:
          name: deploy-to-dev-indexer
          requires:
            - deployment-test
            - approve-deploy-indexer

          environment: development
          root: _deployment/indexer
          # filters:
          #   branches:
          #     only:
          #       - main

      - deploy_to_cluster:
          name: deploy-to-staging-api
          requires:
            - deployment-test
            - approve-deploy-client-api-staging
          environment: staging
          root: _deployment
          # filters:
          #   branches:
          #     only:
          #       - main

      - deploy_to_cluster:
          name: deploy-to-staging-indexer
          requires:
            - deployment-test
            - approve-deploy-indexer-staging
          environment: staging
          root: _deployment/indexer
          # filters:
          #   branches:
          #     only:
          #       - main
