sources:
  - name: polygon-indexer
    handler:
      graphql:
        endpoint: ${POLYGON_INDEXER_GRAPHQL_ENDPOINT}
        source: ./src/sources/indexer/schema.graphql
    transforms:
      - rename:
          mode: bare | wrap
          renames:
            - from:
                type: OwnershipContract
              to:
                type: Contract
            - from:
                type: Contract
                field: id
              to:
                type: Contract
                field: address
            - from:
                type: Query
                field: ownershipContracts
              to:
                type: Query
                field: contracts
            - from:
                type: OwnershipContractWhereInput
                field: id_eq
              to:
                type: OwnershipContractWhereInput
                field: address_eq
      - filterSchema:
          mode: bare | wrap
          filters:
            - Type.!{ OwnershipContractsConnection, OwnershipContractEdge, OwnershipContractOrderByInput}
            - Query.!{ownershipContractById, ownershipContractByUniqueInput, ownershipContractsConnection}
            - Query.contracts.!orderBy
      - encapsulate:
          name: polygon
          applyTo:
            query: true
  - name: ethereum-indexer
    handler:
      graphql:
        endpoint: ${ETHEREUM_INDEXER_GRAPHQL_ENDPOINT}
        source: ./src/sources/indexer/schema.graphql
    transforms:
      - rename:
          mode: bare | wrap
          renames:
            - from:
                type: OwnershipContract
              to:
                type: Contract
            - from:
                type: Contract
                field: id
              to:
                type: Contract
                field: address
            - from:
                type: Query
                field: ownershipContracts
              to:
                type: Query
                field: contracts
            - from:
                type: OwnershipContractWhereInput
                field: id_eq
              to:
                type: OwnershipContractWhereInput
                field: address_eq
      - filterSchema:
          mode: bare | wrap
          filters:
            - Type.!{ OwnershipContractsConnection, OwnershipContractEdge, OwnershipContractOrderByInput}
            - Query.!{ownershipContractById, ownershipContractByUniqueInput, ownershipContractsConnection}
            - Query.contracts.!orderBy
      - encapsulate:
          name: ethereum
          applyTo:
            query: true
      
  - name: api-client
    handler:
      graphql:
        endpoint: ${API_GRAPHQL_ENDPOINT}
        source: ./src/sources/api-client/schema.graphql

additionalEnvelopPlugins: './src/authPlugin.ts'