sources:
  - name: Service1
    handler:
      graphql:
        endpoint: https://indexer.gorengine.com/graphql
  - name: Service2
    handler:
      graphql:
        endpoint: http://laos-client-api.protostar.svc.cluster.local:4001/
        source: ./src/sources/api-client/schema.graphql

additionalEnvelopPlugins: './src/authPlugin.ts'