sources:
  - name: polygon-indexer
    handler:
      graphql:
        endpoint: ${POLYGON_INDEXER_GRAPHQL_ENDPOINT}
        source: ./src/sources/indexer/schema.graphql
    transforms:
      - encapsulate:
          name: polygon
          applyTo:
            query: true
  - name: ethereum-indexer
    handler:
      graphql:
        endpoint: ${ETHEREUM_INDEXER_GRAPHQL_ENDPOINT}
        source: ./src/sources/indexer/schema.graphql
    transforms:
      - encapsulate:
          name: ethereum
          applyTo:
            query: true
  - name: api-client
    handler:
      graphql:
        endpoint: ${API_GRAPHQL_ENDPOINT}
        source: ./src/sources/api-client/schema.graphql

additionalEnvelopPlugins: './src/authPlugin.ts'