repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true

namespace: goalrev

releases:
  - name: public-node-protostar
    chart: parity/node
    version: 5.5.1
    values:
      - image:
          repository: freeverseio/laos-node
          tag: "v0.22.0"
      - node:
          replicas: 1
          chain: laos-sigma
          command: "laos"
          isParachain: true
          telemetryUrls:
            - 'wss://telemetry.polkadot.io/submit 0'
          chainData:
            volumeSize: 256Gi
            pruning: false
          flags:
            - "--pruning=archive"
            - "--rpc-max-connections=500"
          perNodeServices:
            apiService:
              enabled: true
            setPublicAddressToExternalIp:
              enabled: true
              autodiscoveryFix: true
            paraP2pService:
              enabled: true
              type: NodePort
          collatorRelayChain:
            chainData:
              volumeSize: 512Gi
            flags:
              - --sync=fast